---
title: "Explore resilience evi"
author: "AJ Perez-Luque (@ajpelu)"
date: "2017 Aug"
output: pdf_document
---
```{r, echo=FALSE, message=FALSE}
require(knitr)
opts_chunk$set(fig.align='center', message = FALSE, warning = FALSE) 
```

```{r wd, echo=FALSE}
#---------------------------------
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_modis_resilience', sep='')
#---------------------------------
```


```{r packages, warning=FALSE, message=FALSE, echo=FALSE}
library('dplyr')
library('tidyverse')
library('broom')
library('pander')
library('lsmeans')
library('effects')
library('gridExtra')
```

# Prepare data 

```{r}
# Read data
raw_evires <- read.csv(file=paste(di, "/data/resilience/resiliences.csv", sep=""), header = TRUE, sep = ',')

# add data of pop
anomalias <- read.csv(file=paste(di, "/data/anomalies/anomalias_evimean.csv", sep=""), header = TRUE, sep = ',')

attr_iv_malla_modis_id <- anomalias %>% dplyr::select(iv_malla_modi_id,long,lat,pop) %>% unique()
  

raw_evires <- raw_evires %>% inner_join(attr_iv_malla_modis_id, by='iv_malla_modi_id')

# filter by pop and add new variable

evires <- raw_evires %>% 
  mutate(
    clu_pop = as.factor(case_when(
      pop == 1 ~ "Camarate",
      pop %in% c(2,3,4,5) ~ 'Northern slope',
      pop %in% c(6,7,8) ~ 'Southern slope',
      pop == 9 ~ 'out')),
    clu_pop2 = as.factor(case_when(
      pop %in% c(1,2,3,4,5) ~ 'Northern slope',
      pop %in% c(6,7,8) ~ 'Southern slope',
      pop == 9 ~ 'out'))) %>% 
  filter(clu_pop != 'out')

# Change name of clu_pop2 and disturb_year para los analisis anovas
evires <- evires %>% rename(site = clu_pop2) %>% 
  mutate(disturb_year = as.factor(disturb_year))

```


```{r, echo=FALSE}
# Custom Function to compute ANOVAS
aovas <- function(df, vars, resp_var){ 
  require('dplyr')
  require('broom')
  
  # Create subset 
  dfsel <- df %>% dplyr::select_(.dots=c(vars, resp_var)) 
    
  # Model 
  myformula <- as.formula(paste0(resp_var,  " ~ ",
                                 paste(vars, collapse = '*')))
  
  mymodel <- aov(myformula, data=dfsel)
  
  # Output model Summary http://my.ilstu.edu/~wjschne/444/ANOVA.html#(1)
  model_coeff <- broom::tidy(mymodel)
  model_summary <- broom::glance(mymodel)
  
  out <- c() 
  out$model_coeff <- model_coeff
  out$model_summary <- model_summary
  out$mymodel <- mymodel
  
  return(out)
}


# Post-Hoc comparison
phc <- function(mymodel, resp_var){
  require(lsmeans)

  # Disturb Event 
  ph_event <- lsmeans(mymodel, pairwise ~ disturb_year, adjust = "bon")
  
  # differences letters 
  cld_event <- cld(ph_event, alpha   = 0.01, 
                   Letters = letters, 
                   adjust  = "bon")
  
  # Site  
  ph_site <- lsmeans(mymodel, pairwise ~ site, adjust = "bon")
  cld_site <- cld(ph_site, alpha   = 0.01, 
                 Letters = letters, 
                 adjust  = "bon")

  # interaction 
  ph_i <- lsmeans(mymodel, pairwise ~ disturb_year:site, adjust = "bon")
  cld_i <- cld(ph_i, alpha   = 0.01, 
                 Letters = letters, 
                 adjust  = "bon")
  
  # Objets for plot
  aux_ph_site <- as.data.frame(summary(ph_site$lsmeans)) 
  aux_ph_site <- aux_ph_site %>% mutate(var = resp_var)
  aux_ph_event <- as.data.frame(summary(ph_event$lsmeans)) 
  aux_ph_event <- aux_ph_event %>% mutate(var = resp_var)
  aux_ph_i <- as.data.frame(summary(ph_i$lsmeans)) 
  aux_ph_i <- aux_ph_i %>% mutate(var = resp_var)
  
  # Return objects
  cat('\n### Event ###\n')
  print(ph_event)
  print(cld_event)
  cat('\n### Clu pop ###\n')
  print(ph_site)
  print(cld_site)
  cat('\n### Event:Clu pop ###\n')
  print(ph_i)
  return(list(aux_ph_site, aux_ph_event, aux_ph_i, cld_site, cld_event, cld_i))
}
```

## ANOVAs
### Recovery

```{r, echo=FALSE}
resp_var <- 'rc'
vars <- c('disturb_year','site')

# AOV
aov_rc <- aovas(evires, vars=vars, resp_var = resp_var)

mc <- aov_rc$model_coeff

pander(mc, round=5,
       caption = paste0("ANOVA table: ", resp_var), missing = '', 
       emphasize.strong.cells = 
         which(mc < 0.1 & mc == mc$p.value, arr.ind = T))

gm <- aov_rc$model_summary

gm <- apply(gm, 1, formatC, digits = 2, format = "f") %>% t()
colnames(gm) <- paste0("$",c("R^2","\\mathrm{adj}R^2","\\sigma_e","F","p","df_m","\\mathrm{logLik}","AIC","BIC","\\mathrm{dev}","df_e"),"$")
rownames(gm) <- "Statistic"
pander(t(gm)) 
```

```{r}
# Post hoc Define model
mymodel <- aov_rc$mymodel
postH_rc <- phc(mymodel = mymodel, resp_var = resp_var)
```


```{r, echo=FALSE}
#### ~ Site
ps <- plot(effect("site",mymodel))
#### ~ Disturb Year
pd <- plot(effect('disturb_year', mymodel))
#### Disturb Year:Site
picollapse <- plot(effect("disturb_year:site",mymodel), multiline = TRUE, ci.style = 'bars')
pi <- plot(effect("disturb_year:site",mymodel), layout=c(2,1))

``` 

```{r, fig.width = 4, fig.height=4}
ps
```

```{r, fig.width = 4, fig.height=4}
pd
```

```{r, fig.width = 4, fig.height=4}
picollapse
```

```{r, fig.width = 6}
pi
```


### Resistance 
```{r, echo=FALSE}
# Variable
resp_var <- 'rt'

vars <- c('disturb_year','site')

# AOV
aov_rt <- aovas(evires, vars=vars, resp_var = resp_var)

mc <- aov_rt$model_coeff

pander(mc, round=5,
       caption = paste0("ANOVA table: ", resp_var), missing = '', 
       emphasize.strong.cells = 
         which(mc < 0.1 & mc == mc$p.value, arr.ind = T))

gm <- aov_rt$model_summary

gm <- apply(gm, 1, formatC, digits = 2, format = "f") %>% t()
colnames(gm) <- paste0("$",c("R^2","\\mathrm{adj}R^2","\\sigma_e","F","p","df_m","\\mathrm{logLik}","AIC","BIC","\\mathrm{dev}","df_e"),"$")
rownames(gm) <- "Statistic"
pander(t(gm)) 
```

```{r}
# Post hoc Define model
mymodel <- aov_rt$mymodel
postH_rt <- phc(mymodel = mymodel, resp_var = resp_var)
```

```{r, echo=FALSE}
#### ~ Site
ps <- plot(effect("site",mymodel))
#### ~ Disturb Year
pd <- plot(effect('disturb_year', mymodel))
#### Disturb Year:Site
picollapse <- plot(effect("disturb_year:site",mymodel), multiline = TRUE, ci.style = 'bars')
pi <- plot(effect("disturb_year:site",mymodel), layout=c(2,1))

``` 

```{r, fig.width = 4, fig.height=4}
ps
```

```{r, fig.width = 4, fig.height=4}
pd
```

```{r, fig.width = 4, fig.height=4}
picollapse
```

```{r, fig.width = 6}
pi
```

### Resilience 
```{r, echo=FALSE}
# Variable
resp_var <- 'rs'

vars <- c('disturb_year','site')

# AOV
aov_rs <- aovas(evires, vars=vars, resp_var = resp_var)

mc <- aov_rs$model_coeff

pander(mc, round=5,
       caption = paste0("ANOVA table: ", resp_var), missing = '', 
       emphasize.strong.cells = 
         which(mc < 0.1 & mc == mc$p.value, arr.ind = T))

gm <- aov_rs$model_summary

gm <- apply(gm, 1, formatC, digits = 2, format = "f") %>% t()
colnames(gm) <- paste0("$",c("R^2","\\mathrm{adj}R^2","\\sigma_e","F","p","df_m","\\mathrm{logLik}","AIC","BIC","\\mathrm{dev}","df_e"),"$")
rownames(gm) <- "Statistic"
pander(t(gm)) 
```

```{r}
# Post hoc Define model
mymodel <- aov_rs$mymodel
postH_rs <- phc(mymodel = mymodel, resp_var = resp_var)
```

```{r, echo=FALSE}
#### ~ Site
ps <- plot(effect("site",mymodel))
#### ~ Disturb Year
pd <- plot(effect('disturb_year', mymodel))
#### Disturb Year:Site
picollapse <- plot(effect("disturb_year:site",mymodel), multiline = TRUE, ci.style = 'bars')
pi <- plot(effect("disturb_year:site",mymodel), layout=c(2,1))

``` 

```{r, fig.width = 4, fig.height=4}
ps
```

```{r, fig.width = 4, fig.height=4}
pd
```

```{r, fig.width = 4, fig.height=4}
picollapse
```

```{r, fig.width = 6}
pi
```


### Relative Resilience
```{r, echo=FALSE}
# Variable
resp_var <- 'rrs'

vars <- c('disturb_year','site')

# AOV
aov_rrs <- aovas(evires, vars=vars, resp_var = resp_var)

mc <- aov_rrs$model_coeff

pander(mc, round=5,
       caption = paste0("ANOVA table: ", resp_var), missing = '', 
       emphasize.strong.cells = 
         which(mc < 0.1 & mc == mc$p.value, arr.ind = T))

gm <- aov_rrs$model_summary

gm <- apply(gm, 1, formatC, digits = 2, format = "f") %>% t()
colnames(gm) <- paste0("$",c("R^2","\\mathrm{adj}R^2","\\sigma_e","F","p","df_m","\\mathrm{logLik}","AIC","BIC","\\mathrm{dev}","df_e"),"$")
rownames(gm) <- "Statistic"
pander(t(gm)) 
```

```{r}
# Post hoc Define model
mymodel <- aov_rrs$mymodel
postH_rrs <- phc(mymodel = mymodel, resp_var = resp_var)
```

```{r, echo=FALSE}
#### ~ Site
ps <- plot(effect("site",mymodel))
#### ~ Disturb Year
pd <- plot(effect('disturb_year', mymodel))
#### Disturb Year:Site
picollapse <- plot(effect("disturb_year:site",mymodel), multiline = TRUE, ci.style = 'bars')
pi <- plot(effect("disturb_year:site",mymodel), layout=c(2,1))

``` 

```{r, fig.width = 4, fig.height=4}
ps
```

```{r, fig.width = 4, fig.height=4}
pd
```

```{r, fig.width = 4, fig.height=4}
picollapse
```

```{r, fig.width = 6}
pi
```


```{r, echo=FALSE}
means_site <- postH_rc[[4]] %>% mutate(var = 'rc') %>% 
  bind_rows(postH_rt[[4]] %>% mutate(var = 'rt')) %>% 
  bind_rows(postH_rs[[4]] %>% mutate(var = 'rs')) %>% 
  bind_rows(postH_rrs[[4]] %>% mutate(var = 'rrs')) %>% 
  rename(letras = .group)

means_disturb <- postH_rc[[5]] %>% mutate(var = 'rc') %>% 
  bind_rows(postH_rt[[5]] %>% mutate(var = 'rt')) %>% 
  bind_rows(postH_rs[[5]] %>% mutate(var = 'rs')) %>% 
  bind_rows(postH_rrs[[5]] %>% mutate(var = 'rrs')) %>% 
  rename(letras = .group)

means_distub_site <- postH_rc[[6]] %>% mutate(var = 'rc') %>% 
  bind_rows(postH_rt[[6]] %>% mutate(var = 'rt')) %>% 
  bind_rows(postH_rs[[6]] %>% mutate(var = 'rs')) %>% 
  bind_rows(postH_rrs[[6]] %>% mutate(var = 'rrs')) %>% 
  rename(letras = .group)
```


```{r, echo=FALSE}
dodge <- position_dodge(width = 0.3)
micolor <- '#455883'
mierrorbarSE <- aes(ymin=lsmean - SE, ymax=lsmean + SE)
mierrorbar <- aes(ymin=lower.CL, ymax=upper.CL)
```

```{r, echo=FALSE}
plot_ms <- means_site %>%  
  ggplot(aes(x=site, y=lsmean)) + 
  geom_point(colour=micolor, 
             size=3, position = dodge) +
  theme_bw() + xlab('') + ylab('') + 
  facet_wrap(~var, scales='free_y', ncol = 1) +
  geom_text(aes(y=lsmean, label=letras), nudge_x = 0.15) +
  theme(strip.background = element_rect(colour = "black", fill = "white"))

plot_msSE <- plot_ms + geom_errorbar(mierrorbarSE,color=micolor, 
                                     size=.5, width=.15, position = dodge) 

plot_msCI <- plot_ms + geom_errorbar(mierrorbar,color=micolor, 
                                     size=.5, width=.15, position = dodge)
```


```{r, echo=FALSE}
plot_md <- means_disturb %>%  
  ggplot(aes(x=disturb_year, y=lsmean)) + 
  geom_point(colour=micolor, 
             size=3, position = dodge) +
  theme_bw() + xlab('') + ylab('') + 
  facet_wrap(~var, scales='free_y', ncol = 1) +
  geom_text(aes(y=lsmean, label=letras), nudge_x = 0.15) +
  theme(strip.background = element_rect(colour = "black", fill = "white"))


plot_mdSE <- plot_md + geom_errorbar(mierrorbarSE,color=micolor, 
                                     size=.5, width=.15, position = dodge) 

plot_mdCI <- plot_md + geom_errorbar(mierrorbar,color=micolor, 
                                     size=.5, width=.15, position = dodge)
```

```{r, echo=FALSE}
plot_mds <- means_distub_site %>%  
  ggplot(aes(x=site, y=lsmean, group=disturb_year, colour=disturb_year)) + 
  geom_point(aes(shape=disturb_year), size=3) + 
  geom_line() +
  theme_bw() + xlab('') + ylab('') + 
  facet_wrap(~var, scales='free_y', ncol = 1) +
  geom_text(aes(y=lsmean+SE, label=letras), nudge_x = 0.15)+
  theme(strip.background = element_rect(colour = "black", fill = "white"),
        legend.position = c(0.8, 0.93),
        legend.background = element_blank()) +
  scale_colour_manual(values = c(micolor, "red")) 


plot_mdsSE <- plot_mds + geom_errorbar(mierrorbarSE, size=.5, width=.15)
plot_mdsCI <- plot_mds + geom_errorbar(mierrorbar, size=.5, width=.15)
```

### mean + sd
```{r,fig.width = 12, fig.height=12}
grid.arrange(plot_mdSE, plot_msSE, plot_mdsSE, ncol=3)
```



### mean + ci

```{r, fig.width = 12, fig.height=12}
grid.arrange(plot_mdCI, plot_msCI, plot_mdsCI, ncol=3)
```

```{r, echo=FALSE}
pdf(paste0(di, '/images/resilience/interaction_plotsSE.pdf'), width=9, height = 9)
grid.arrange(plot_mdSE, plot_msSE, plot_mdsSE, ncol=3)
dev.off()

pdf(paste0(di, '/images/resilience/interaction_plotsCI.pdf'), width=9, height = 9)
grid.arrange(plot_mdCI, plot_msCI, plot_mdsCI, ncol=3)
dev.off()

```

```{r, echo=FALSE}
aovas_coeff <- aov_rc$model_coeff %>% mutate(var = 'rc') %>% 
  bind_rows(aov_rt$model_coeff %>% mutate(var = 'rt')) %>% 
  bind_rows(aov_rs$model_coeff %>% mutate(var = 'rs')) %>% 
  bind_rows(aov_rrs$model_coeff%>% mutate(var = 'rrs')) 

write.csv(aovas_coeff, file=paste0(di, '/out/anovas_resilience/anovas_statistics.csv'), row.names = F)

aovas_coeff %>% pander()
```

```{r, echo=FALSE}
aovas_model_summary <- aov_rc$model_summary %>% mutate(var = 'rc') %>% 
  bind_rows(aov_rt$model_summary %>% mutate(var = 'rt')) %>% 
  bind_rows(aov_rs$model_summary %>% mutate(var = 'rs')) %>% 
  bind_rows(aov_rrs$model_summary%>% mutate(var = 'rrs')) 

write.csv(aovas_model_summary, 
          file=paste0(di, '/out/anovas_resilience/anovas_summary_modelos.csv'), row.names = F)


gm <- apply(aovas_model_summary, 1, formatC, digits = 2, format = "f") 
rownames(gm) <- paste0("$",c("R^2","\\mathrm{adj}R^2","\\sigma_e","F","p","df_m","\\mathrm{logLik}","AIC","BIC","\\mathrm{dev}","df_e", "variable"),"$")
colnames(gm) <- c("rc", "rt", "rs", "rrs")

pander(gm)
```


